im = imread('../asset/image/436.tif');
[m, n] = size(im);
mask = ones(2*m, 2*n);
mask(1:2:end, 2:2:end) = -1;
mask(2:2:end, 1:2:end) = -1;
f = im2double(im);
subplot(3, 3, 1);
imshow(f);
f(m+1:2*m, :) = 0;
f(:, n+1:2*n) = 0;
subplot(3, 3, 2);
imshow(f);
f = f .* mask;
subplot(3, 3, 3);
imshow(f);
F = fft2(f);
subplot(3, 3, 4);
imshow(log(1+abs(F)), []);
y = -m+1:m;
x = -n+1:n;
H = 1./(1+((x.^2+y'.^2)/900).^2);
subplot(3, 3, 5);
imshow(log(1+abs(H)), []);
G = H .* F;
subplot(3, 3, 6);
imshow(log(1+abs(G)), []);
g = real(ifft2(G));
g = g .* mask;
subplot(3, 3, 7);
imshow(g);
g = g(1:m, 1:n);
subplot(3, 3, 8);
imshow(g);
saveas(gcf, '../asset/result/436.png');